//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageProvidersTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageProvidersTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; class=&quot;en&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;Pinterest / Home &lt;/title&gt;
        ///        
        ///        &lt;link rel=&quot;icon&quot; href=&quot;http://passets-lt.pinterest.com/images/favicon.png&quot; type=&quot;image/x-icon&quot; /&gt;
        ///        &lt;link rel=&quot;apple-touch-icon-precomposed&quot; href=&quot;http://passets-ec.pinterest.com/images/ipad_touch_icon.png&quot; /&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;http://passets-lt.pinterest.com/css/pinboard_1c320d6e.css&quot; type=&quot;text/css&quot; media=&quot;all&quot;/&gt;
        ///        &lt;!--[if (gt IE 6)&amp;(lt IE 9)]&gt;&lt;link rel=&quot;styleshee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pinterestsamplepage {
            get {
                return ResourceManager.GetString("pinterestsamplepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;kind&quot;: &quot;Listing&quot;, &quot;data&quot;: {&quot;modhash&quot;: &quot;&quot;, &quot;children&quot;: [{&quot;kind&quot;: &quot;t3&quot;, &quot;data&quot;: {&quot;domain&quot;: &quot;i.imgur.com&quot;, &quot;banned_by&quot;: null, &quot;media_embed&quot;: {}, &quot;subreddit&quot;: &quot;aww&quot;, &quot;selftext_html&quot;: null, &quot;selftext&quot;: &quot;&quot;, &quot;likes&quot;: null, &quot;link_flair_text&quot;: null, &quot;id&quot;: &quot;zq1zc&quot;, &quot;clicked&quot;: false, &quot;title&quot;: &quot;Not a cat or dog.. but made me smile &quot;, &quot;num_comments&quot;: 243, &quot;score&quot;: 2918, &quot;approved_by&quot;: null, &quot;over_18&quot;: false, &quot;hidden&quot;: false, &quot;thumbnail&quot;: &quot;http://a.thumbs.redditmedia.com/eBMMe_wJtPtZNoYN.jpg&quot;, &quot;subreddit_id&quot;: &quot;t5_2qh1o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string redditsamplepage {
            get {
                return ResourceManager.GetString("redditsamplepage", resourceCulture);
            }
        }
    }
}
